# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/llcze/Desktop/ui_files/weather_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_weatherapp(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(555, 353)
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(85, 255, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(255, 170, 0);\n"
"background-color: rgba(0,0,0,0%);")
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.city_name = QtWidgets.QLabel(self.centralwidget)
        self.city_name.setGeometry(QtCore.QRect(270, 0, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.city_name.setFont(font)
        self.city_name.setAutoFillBackground(False)
        self.city_name.setStyleSheet("color:rgb(125, 125, 125);\n"
"background-color: rgba(0,0,0,0%);")
        self.city_name.setTextFormat(QtCore.Qt.AutoText)
        self.city_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.city_name.setObjectName("city_name")
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(30, 80, 191, 181))
        self.icon.setStyleSheet("background-color: rbga(0,0,0,0%)")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("C:\\Users\\llcze\\Desktop\\icons\\weather\sun.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.weather_status = QtWidgets.QLabel(self.centralwidget)
        self.weather_status.setGeometry(QtCore.QRect(10, 270, 221, 51))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.weather_status.setFont(font)
        self.weather_status.setStyleSheet("background-color: rgba(0,0,0,0%);")
        self.weather_status.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_status.setObjectName("weather_status")
        self.temp_label = QtWidgets.QLabel(self.centralwidget)
        self.temp_label.setGeometry(QtCore.QRect(270, 80, 281, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.temp_label.setFont(font)
        self.temp_label.setStyleSheet("background-color: rgba(0,0,0,0%);")
        self.temp_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.temp_label.setObjectName("temp_label")
        self.feels_label = QtWidgets.QLabel(self.centralwidget)
        self.feels_label.setGeometry(QtCore.QRect(270, 120, 281, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.feels_label.setFont(font)
        self.feels_label.setStyleSheet("background-color: rgba(0,0,0,0%);")
        self.feels_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.feels_label.setObjectName("feels_label")
        self.humid_label = QtWidgets.QLabel(self.centralwidget)
        self.humid_label.setGeometry(QtCore.QRect(270, 160, 281, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.humid_label.setFont(font)
        self.humid_label.setStyleSheet("background-color: rgba(0,0,0,0%);")
        self.humid_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.humid_label.setObjectName("humid_label")
        self.pressure_label = QtWidgets.QLabel(self.centralwidget)
        self.pressure_label.setGeometry(QtCore.QRect(270, 200, 281, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pressure_label.setFont(font)
        self.pressure_label.setStyleSheet("background-color: rgba(0,0,0,0%);")
        self.pressure_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pressure_label.setObjectName("pressure_label")
        self.wind_label = QtWidgets.QLabel(self.centralwidget)
        self.wind_label.setGeometry(QtCore.QRect(270, 240, 281, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.wind_label.setFont(font)
        self.wind_label.setStyleSheet("background-color: rgba(0,0,0,0%);")
        self.wind_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wind_label.setObjectName("wind_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 26))
        self.menubar.setStyleSheet("background-color:rgb(255, 255, 255)\n"
"")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionZip = QtWidgets.QAction(MainWindow)
        self.actionZip.setObjectName("actionZip")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionZip)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WeatherApp"))
        self.title.setText(_translate("MainWindow", "DailyWeather"))
        self.city_name.setText(_translate("MainWindow", "Millersville"))
        self.weather_status.setText(_translate("MainWindow", "Sunny"))
        self.temp_label.setText(_translate("MainWindow", "Temperature: "))
        self.feels_label.setText(_translate("MainWindow", "Feels Like: "))
        self.humid_label.setText(_translate("MainWindow", "Humidity: "))
        self.pressure_label.setText(_translate("MainWindow", "Air Pressure: "))
        self.wind_label.setText(_translate("MainWindow", "Windspeed: "))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionZip.setText(_translate("MainWindow", "Change Zip"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
